### ISSUE TITLE
Keep getting Error while connecting

### ISSUE THREAD

**Issue by jeroenpeters1986** [tinify/tinify-python#2]
I have a valid API key. If I run tinify.validate() I get a True returned.

When I want to use the from_file method, I keep getting the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jeroen/.virtualenvs/dingen/lib/python2.7/site-packages/tinify/__init__.py", line 65, in from_file
    return Source.from_file(path)
  File "/home/jeroen/.virtualenvs/dingen/lib/python2.7/site-packages/tinify/source.py", line 14, in from_file
    return cls._shrink(f.read())
  File "/home/jeroen/.virtualenvs/dingen/lib/python2.7/site-packages/tinify/source.py", line 26, in _shrink
    response = tinify.get_client().request('POST', '/shrink', obj)
  File "/home/jeroen/.virtualenvs/dingen/lib/python2.7/site-packages/tinify/client.py", line 52, in request
    raise ConnectionError('Error while connecting: {0}'.format(err), cause=err)
tinify.errors.ConnectionError: Error while connecting: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```

I am not sure what's wrong. The file is accessible and Python is able to read it.

**Comment by jeroenpeters1986** [comment]
Closing this issue, PEBKAC, requests lib wasn't updated although it is a requirement. Manually upgrading it fixes this..
